/* The following code was generated by JFlex 1.4.3 on 06/10/15 03:13 PM */

package sgbd.lexico;

import java_cup.runtime.*;
import java.util.ArrayList;
import lema.analizadorSemantico.Nodo;
import sgbd.Mistake;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 06/10/15 03:13 PM from the specification file
 * <tt>/home/yuli/NetBeansProjects/SGBD/src/sgbd/lexico/Lexer.flex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\6\2\0\1\3\22\0\1\3\1\0\1\40\5\0"+
    "\1\26\1\27\1\5\1\0\1\30\1\0\1\41\1\4\12\2\1\0"+
    "\1\32\1\0\1\31\3\0\1\23\1\20\1\24\1\15\1\12\1\36"+
    "\1\13\1\25\1\7\2\1\1\21\1\37\1\10\1\16\1\34\1\1"+
    "\1\14\1\33\1\11\1\17\1\22\1\35\3\1\4\0\1\52\1\0"+
    "\1\47\3\1\1\45\1\46\5\1\1\50\5\1\1\43\1\51\1\42"+
    "\1\44\5\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\7\2"+
    "\1\6\1\7\1\10\1\11\1\12\3\2\1\1\2\2"+
    "\1\0\1\4\1\0\17\2\1\0\1\13\2\2\1\14"+
    "\1\0\7\2\1\15\5\2\1\16\7\2\1\17\3\2"+
    "\1\20\10\2\1\21\1\2\1\22\1\23\3\2\1\24"+
    "\11\2\1\25\1\26\1\2\1\27\1\30\1\31\1\32"+
    "\1\2\1\33\2\2\1\34\1\35\1\36\1\37\1\2"+
    "\1\40\1\41\1\42\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\53\0\254\0\53\0\327"+
    "\0\u0102\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\53\0\53"+
    "\0\53\0\53\0\53\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0"+
    "\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408"+
    "\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df\0\u050a\0\u0535\0\u0560"+
    "\0\u058b\0\u05b6\0\u05e1\0\u0285\0\53\0\u060c\0\u0637\0\u0306"+
    "\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764\0\u078f"+
    "\0\126\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\126\0\u0891"+
    "\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968\0\u0993\0\126\0\u09be"+
    "\0\u09e9\0\u0a14\0\126\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb"+
    "\0\u0b16\0\u0b41\0\u0b6c\0\126\0\u0b97\0\126\0\126\0\u0bc2"+
    "\0\u0bed\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a"+
    "\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\126\0\126\0\u0df1\0\126"+
    "\0\126\0\126\0\126\0\u0e1c\0\126\0\u0e47\0\u0e72\0\126"+
    "\0\126\0\126\0\126\0\u0e9d\0\126\0\126\0\u0ec8\0\126";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\5\1\10"+
    "\1\3\1\11\3\3\1\12\1\3\1\13\1\14\1\3"+
    "\1\15\1\3\1\16\1\3\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\3\1\25\1\26\1\3\1\27\1\2"+
    "\1\30\3\3\1\31\3\3\1\2\54\0\2\3\4\0"+
    "\17\3\5\0\5\3\2\0\11\3\2\0\1\4\36\0"+
    "\1\32\15\0\1\33\1\34\46\0\2\3\4\0\1\3"+
    "\1\35\15\3\5\0\5\3\2\0\11\3\1\0\2\3"+
    "\4\0\14\3\1\36\2\3\5\0\5\3\2\0\11\3"+
    "\1\0\2\3\4\0\3\3\1\37\1\3\1\40\1\3"+
    "\1\41\4\3\1\42\2\3\5\0\5\3\2\0\11\3"+
    "\1\0\2\3\4\0\17\3\5\0\1\43\1\44\3\3"+
    "\2\0\11\3\1\0\2\3\4\0\7\3\1\45\7\3"+
    "\5\0\5\3\2\0\11\3\1\0\2\3\4\0\14\3"+
    "\1\46\2\3\5\0\5\3\2\0\11\3\1\0\2\3"+
    "\4\0\5\3\1\47\11\3\5\0\5\3\2\0\11\3"+
    "\1\0\2\3\4\0\3\3\1\50\12\3\1\51\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\16\3\1\52"+
    "\5\0\5\3\2\0\11\3\1\0\2\3\4\0\5\3"+
    "\1\53\11\3\5\0\5\3\2\0\11\3\6\54\1\0"+
    "\31\54\1\55\12\54\1\0\2\3\4\0\17\3\5\0"+
    "\5\3\2\0\1\3\1\56\7\3\1\0\2\3\4\0"+
    "\17\3\5\0\5\3\2\0\5\3\1\57\3\3\2\0"+
    "\1\60\50\0\6\33\1\0\44\33\5\34\1\61\45\34"+
    "\1\0\2\3\4\0\2\3\1\62\14\3\5\0\1\63"+
    "\4\3\2\0\11\3\1\0\2\3\4\0\11\3\1\64"+
    "\5\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\12\3\1\65\4\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\7\3\1\66\7\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\10\3\1\67\6\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\2\3\1\70"+
    "\14\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\3\3\1\71\13\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\6\3\1\72\10\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\7\3\1\73\7\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\5\3\1\74"+
    "\4\3\1\75\4\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\3\3\1\76\13\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\2\3\1\77\7\3\1\100"+
    "\4\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\7\3\1\101\7\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\3\3\1\102\13\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\7\3\1\103\7\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\17\3\5\0"+
    "\5\3\2\0\2\3\1\104\6\3\1\0\2\3\4\0"+
    "\17\3\5\0\5\3\2\0\6\3\1\105\2\3\4\34"+
    "\1\5\1\61\45\34\1\0\2\3\4\0\3\3\1\106"+
    "\3\3\1\107\7\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\3\3\1\110\13\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\12\3\1\111\4\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\3\3\1\112"+
    "\13\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\17\3\5\0\1\3\1\113\3\3\2\0\11\3\1\0"+
    "\2\3\4\0\11\3\1\114\5\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\14\3\1\115\2\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\14\3\1\116"+
    "\2\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\12\3\1\117\4\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\15\3\1\120\1\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\10\3\1\121\6\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\14\3\1\122"+
    "\2\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\3\3\1\123\13\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\17\3\5\0\2\3\1\124\2\3\2\0"+
    "\11\3\1\0\2\3\4\0\5\3\1\125\11\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\17\3\5\0"+
    "\4\3\1\126\2\0\11\3\1\0\2\3\4\0\17\3"+
    "\5\0\5\3\2\0\3\3\1\127\5\3\1\0\2\3"+
    "\4\0\17\3\5\0\5\3\2\0\7\3\1\130\1\3"+
    "\1\0\2\3\4\0\4\3\1\131\12\3\5\0\5\3"+
    "\2\0\11\3\1\0\2\3\4\0\5\3\1\132\11\3"+
    "\5\0\5\3\2\0\11\3\1\0\2\3\4\0\3\3"+
    "\1\133\13\3\5\0\5\3\2\0\11\3\1\0\2\3"+
    "\4\0\2\3\1\134\14\3\5\0\5\3\2\0\11\3"+
    "\1\0\2\3\4\0\12\3\1\135\4\3\5\0\5\3"+
    "\2\0\11\3\1\0\2\3\4\0\11\3\1\136\5\3"+
    "\5\0\5\3\2\0\11\3\1\0\2\3\4\0\2\3"+
    "\1\137\14\3\5\0\5\3\2\0\11\3\1\0\2\3"+
    "\4\0\3\3\1\140\13\3\5\0\5\3\2\0\11\3"+
    "\1\0\2\3\4\0\16\3\1\141\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\3\3\1\142\13\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\2\3\1\143"+
    "\14\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\15\3\1\144\1\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\3\3\1\145\13\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\17\3\5\0\5\3\2\0"+
    "\3\3\1\146\5\3\1\0\2\3\4\0\3\3\1\147"+
    "\13\3\5\0\5\3\2\0\11\3\1\0\2\3\4\0"+
    "\2\3\1\150\14\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\17\3\5\0\1\151\4\3\2\0\11\3"+
    "\1\0\2\3\4\0\3\3\1\152\13\3\5\0\5\3"+
    "\2\0\11\3\1\0\2\3\4\0\3\3\1\153\13\3"+
    "\5\0\5\3\2\0\11\3\1\0\2\3\4\0\14\3"+
    "\1\154\2\3\5\0\5\3\2\0\11\3\1\0\2\3"+
    "\4\0\3\3\1\155\13\3\5\0\5\3\2\0\11\3"+
    "\1\0\2\3\4\0\14\3\1\156\2\3\5\0\5\3"+
    "\2\0\11\3\1\0\2\3\4\0\14\3\1\157\2\3"+
    "\5\0\5\3\2\0\11\3\1\0\2\3\4\0\17\3"+
    "\5\0\1\160\4\3\2\0\11\3\1\0\2\3\4\0"+
    "\3\3\1\161\13\3\5\0\5\3\2\0\11\3\1\0"+
    "\2\3\4\0\2\3\1\162\14\3\5\0\5\3\2\0"+
    "\11\3\1\0\2\3\4\0\5\3\1\163\11\3\5\0"+
    "\5\3\2\0\11\3\1\0\2\3\4\0\17\3\5\0"+
    "\1\164\4\3\2\0\11\3\1\0\2\3\4\0\1\3"+
    "\1\165\15\3\5\0\5\3\2\0\11\3\1\0\2\3"+
    "\4\0\5\3\1\166\11\3\5\0\5\3\2\0\11\3"+
    "\1\0\2\3\4\0\3\3\1\167\13\3\5\0\5\3"+
    "\2\0\11\3\1\0\2\3\4\0\17\3\5\0\1\170"+
    "\4\3\2\0\11\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3827];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\1\11\7\1\5\11"+
    "\6\1\1\0\1\1\1\0\17\1\1\0\1\11\3\1"+
    "\1\0\107\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /** Variable encargada de guardar errores léxicos */
    public Mistake e;
    
    /**
        * Constructor de clase Lexico.
        *
        * @param    in  lectura de entrada.
        * @param    e   errores encontrados por el compilador.    
    */    
    public Lexico(java.io.Reader in, Mistake e)
    {
        this.e = e;
        this.zzReader = in;
    }
    
    /**
        * Crea un nuevo token no terminal encontrado.
        *
        * @param    type    código del token aceptado por LeMa.
        * @return   nuevo   <tt>Symbol</tt> creado para almacenar al token
    */
    private Symbol symbol(int type)
    {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /**
        * Crea un nuevo token terminal encontrado.
        *
        * @param    type    código del token aceptado por LeMa.
        * @param    value   estructura que almacena tokens terminales.
        * @return   nuevo   <tt>Symbol</tt> creado para almacenar al token.
    */
    private Symbol symbol(int type, Object value)
    {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 34: 
          { return symbol(sym.database);
          }
        case 36: break;
        case 35: 
          { return symbol(sym.databases);
          }
        case 37: break;
        case 30: 
          { return symbol(sym.select);
          }
        case 38: break;
        case 26: 
          { return symbol(sym.real,  (new Nodo(sym.real, yytext(), yyline, yycolumn, null, true)));
          }
        case 39: break;
        case 7: 
          { return symbol(sym.par_ce);
          }
        case 40: break;
        case 31: 
          { return symbol(sym.integer,   (new Nodo(sym.integer, yytext(), yyline, yycolumn, null, true)));
          }
        case 41: break;
        case 27: 
          { return symbol(sym.update);
          }
        case 42: break;
        case 10: 
          { return symbol(sym.fin);
          }
        case 43: break;
        case 29: 
          { return symbol(sym.create);
          }
        case 44: break;
        case 12: 
          { return symbol(sym.numreal,       (new Nodo(sym.numreal, yytext(), yyline, yycolumn, null, true)));
          }
        case 45: break;
        case 6: 
          { return symbol(sym.par_ab);
          }
        case 46: break;
        case 32: 
          { return symbol(sym.bool,    (new Nodo(sym.bool, yytext(), yyline, yycolumn, null, true)));
          }
        case 47: break;
        case 23: 
          { return symbol(sym.insert);
          }
        case 48: break;
        case 16: 
          { return symbol(sym.drop);
          }
        case 49: break;
        case 33: 
          { return symbol(sym.varchar,    (new Nodo(sym.varchar, yytext(), yyline, yycolumn, null, true)));
          }
        case 50: break;
        case 25: 
          { return symbol(sym.delete);
          }
        case 51: break;
        case 19: 
          { return symbol(sym.tr,         (new Nodo(sym.tr, yytext(), yyline, yycolumn, null, true)) );
          }
        case 52: break;
        case 5: 
          { return symbol(sym.all);
          }
        case 53: break;
        case 28: 
          { return symbol(sym.values);
          }
        case 54: break;
        case 22: 
          { return symbol(sym.fa,         (new Nodo(sym.fa, yytext(), yyline, yycolumn, null, true)) );
          }
        case 55: break;
        case 21: 
          { return symbol(sym.where);
          }
        case 56: break;
        case 9: 
          { return symbol(sym.igual);
          }
        case 57: break;
        case 15: 
          { return symbol(sym.into);
          }
        case 58: break;
        case 20: 
          { return symbol(sym.table);
          }
        case 59: break;
        case 8: 
          { return symbol(sym.coma);
          }
        case 60: break;
        case 1: 
          { String[] datos = {yytext(),
                                                    String.valueOf(yyline + 1),
                                                    String.valueOf(yycolumn)};
                                  e.insertarError(0, 0, datos);
          }
        case 61: break;
        case 2: 
          { return symbol(sym.id,         (new Nodo(sym.id, yytext(), yyline, yycolumn, null, true)) );
          }
        case 62: break;
        case 24: 
          { return symbol(sym.tables);
          }
        case 63: break;
        case 3: 
          { return symbol(sym.numero,     (new Nodo(sym.numero, yytext(), yyline, yycolumn, null, true)));
          }
        case 64: break;
        case 18: 
          { return symbol(sym.from);
          }
        case 65: break;
        case 11: 
          { return symbol(sym.cadena,     (new Nodo(sym.cadena, yytext(), yyline, yycolumn, null, true)));
          }
        case 66: break;
        case 17: 
          { return symbol(sym.show);
          }
        case 67: break;
        case 14: 
          { return symbol(sym.set);
          }
        case 68: break;
        case 13: 
          { return symbol(sym.use);
          }
        case 69: break;
        case 4: 
          { 
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
